#!/bin/bash
 mvn archetype:generate \
  -DarchetypeArtifactId=android-quickstart \
  -DarchetypeGroupId=de.akquinet.android.archetypes \
  -DarchetypeVersion=1.0.7 \
  -DgroupId=mcmanager \
  -DartifactId=android-center \
  -Dplatform=13